apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: odh-codeflare-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: odh-codeflare-operator
    app.kubernetes.io/part-of: codeflare
  name: odh-codeflare-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: odh-codeflare-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: odh-codeflare-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/codeflare/odh-codeflare-operator@sha256:52a6f8b4813231c0acc05458a03ae9d5014bff3168d36d699e7ea757b2cb78e7
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
